In [1]:
import torch

In [2]:
a = torch.tensor(range(6))
a

tensor([0, 1, 2, 3, 4, 5])

In [4]:
print(a.device)
print(a.dtype)
print(a.to(float))

cpu
torch.int64
tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64)


In [ ]:
print(a.shape)
print(a.view(2,3)) # like reshape

torch.Size([6])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [15]:
a = a.view(1,6,1)
a

tensor([[[0],
         [1],
         [2],
         [3],
         [4],
         [5]]])

In [ ]:

a.squeeze() # removes dimensions of size 1

tensor([0, 1, 2, 3, 4, 5])

In [35]:
print(a)
print(a.squeeze(dim=0)) # removes the first dimension if it is of size 1
print(a.squeeze(dim=2))

tensor([[[0],
         [1],
         [2],
         [3],
         [4],
         [5]]])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5]])
tensor([[0, 1, 2, 3, 4, 5]])


In [20]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
torch.randn(2,3)

tensor([[ 0.4686,  0.7303,  0.9421],
        [-0.6567,  1.0480, -0.6986]])

In [40]:
print(a.view(2, 3)[1, 1])
print(a.view(2, 3)[1, 1].item()) # removes a single value from a tensor and returns it as a Python number

tensor(4)
4


In [43]:
a.numpy() # converts a tensor to a numpy array, if it is on CPU

array([[[0],
        [1],
        [2],
        [3],
        [4],
        [5]]])